server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
#        - id: after_route
#          uri: https://yupi.icu
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        - id: add_request_header_route
          uri: http://localhost:8123/api
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=yupi, swag
#        - id: after_route
#          uri: https://baidu.com
#          predicates:
#            Path=/baidu/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace